services:
  github-runner:
    build: .
    container_name: github-runner
    restart: unless-stopped

    environment:
      GITHUB_URL: ${GITHUB_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
      RUNNER_LABELS: ${RUNNER_LABELS}

    volumes:
      - runner-data:/actions-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  runner-data: